/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrizesRouteImport } from './routes/prizes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorSubmissionsRouteImport } from './routes/mentor.submissions'
import { Route as MentorReviewHistoryRouteImport } from './routes/mentor.review-history'
import { Route as MentorDashboardRouteImport } from './routes/mentor.dashboard'
import { Route as MemberTeamRouteImport } from './routes/member.team'
import { Route as MemberSubmissionRouteImport } from './routes/member.submission'
import { Route as MemberStatusRouteImport } from './routes/member.status'
import { Route as MemberDashboardRouteImport } from './routes/member.dashboard'
import { Route as JudgeProjectsRouteImport } from './routes/judge.projects'
import { Route as JudgeDashboardRouteImport } from './routes/judge.dashboard'
import { Route as JudgeCompletedRouteImport } from './routes/judge.completed'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSubmissionRouteImport } from './routes/app.submission'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AdminWinnersRouteImport } from './routes/admin.winners'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminShortlistRouteImport } from './routes/admin.shortlist'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminScoresRouteImport } from './routes/admin.scores'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminMentorsRouteImport } from './routes/admin.mentors'
import { Route as AdminMentorAssignmentsRouteImport } from './routes/admin.mentor-assignments'
import { Route as AdminJudgesRouteImport } from './routes/admin.judges'
import { Route as AdminJudgeAssignmentsRouteImport } from './routes/admin.judge-assignments'
import { Route as AdminExportsRouteImport } from './routes/admin.exports'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as MentorSubmissionsSubmissionIdRouteImport } from './routes/mentor.submissions.$submissionId'
import { Route as JudgeProjectsSubmissionIdRouteImport } from './routes/judge.projects.$submissionId'
import { Route as AppTeamInviteRouteImport } from './routes/app.team.invite'
import { Route as AppSubmissionStatusRouteImport } from './routes/app.submission.status'
import { Route as AppSubmissionPreviewRouteImport } from './routes/app.submission.preview'
import { Route as AppSubmissionConfirmationRouteImport } from './routes/app.submission.confirmation'
import { Route as AppSubmissionClarificationRouteImport } from './routes/app.submission.clarification'

const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesRoute = PrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorSubmissionsRoute = MentorSubmissionsRouteImport.update({
  id: '/mentor/submissions',
  path: '/mentor/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorReviewHistoryRoute = MentorReviewHistoryRouteImport.update({
  id: '/mentor/review-history',
  path: '/mentor/review-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorDashboardRoute = MentorDashboardRouteImport.update({
  id: '/mentor/dashboard',
  path: '/mentor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberTeamRoute = MemberTeamRouteImport.update({
  id: '/member/team',
  path: '/member/team',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberSubmissionRoute = MemberSubmissionRouteImport.update({
  id: '/member/submission',
  path: '/member/submission',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberStatusRoute = MemberStatusRouteImport.update({
  id: '/member/status',
  path: '/member/status',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberDashboardRoute = MemberDashboardRouteImport.update({
  id: '/member/dashboard',
  path: '/member/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeProjectsRoute = JudgeProjectsRouteImport.update({
  id: '/judge/projects',
  path: '/judge/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeDashboardRoute = JudgeDashboardRouteImport.update({
  id: '/judge/dashboard',
  path: '/judge/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeCompletedRoute = JudgeCompletedRouteImport.update({
  id: '/judge/completed',
  path: '/judge/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/app/team',
  path: '/app/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubmissionRoute = AppSubmissionRouteImport.update({
  id: '/app/submission',
  path: '/app/submission',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/app/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWinnersRoute = AdminWinnersRouteImport.update({
  id: '/admin/winners',
  path: '/admin/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShortlistRoute = AdminShortlistRouteImport.update({
  id: '/admin/shortlist',
  path: '/admin/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScoresRoute = AdminScoresRouteImport.update({
  id: '/admin/scores',
  path: '/admin/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/admin/participants',
  path: '/admin/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/admin/mentors',
  path: '/admin/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMentorAssignmentsRoute = AdminMentorAssignmentsRouteImport.update({
  id: '/admin/mentor-assignments',
  path: '/admin/mentor-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJudgesRoute = AdminJudgesRouteImport.update({
  id: '/admin/judges',
  path: '/admin/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJudgeAssignmentsRoute = AdminJudgeAssignmentsRouteImport.update({
  id: '/admin/judge-assignments',
  path: '/admin/judge-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportsRoute = AdminExportsRouteImport.update({
  id: '/admin/exports',
  path: '/admin/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorSubmissionsSubmissionIdRoute =
  MentorSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => MentorSubmissionsRoute,
  } as any)
const JudgeProjectsSubmissionIdRoute =
  JudgeProjectsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => JudgeProjectsRoute,
  } as any)
const AppTeamInviteRoute = AppTeamInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppSubmissionStatusRoute = AppSubmissionStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppSubmissionRoute,
} as any)
const AppSubmissionPreviewRoute = AppSubmissionPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppSubmissionRoute,
} as any)
const AppSubmissionConfirmationRoute =
  AppSubmissionConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => AppSubmissionRoute,
  } as any)
const AppSubmissionClarificationRoute =
  AppSubmissionClarificationRouteImport.update({
    id: '/clarification',
    path: '/clarification',
    getParentRoute: () => AppSubmissionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/prizes': typeof PrizesRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/timeline': typeof TimelineRoute
  '/tracks': typeof TracksRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/judge-assignments': typeof AdminJudgeAssignmentsRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/mentor-assignments': typeof AdminMentorAssignmentsRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shortlist': typeof AdminShortlistRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/submission': typeof AppSubmissionRouteWithChildren
  '/app/team': typeof AppTeamRouteWithChildren
  '/judge/completed': typeof JudgeCompletedRoute
  '/judge/dashboard': typeof JudgeDashboardRoute
  '/judge/projects': typeof JudgeProjectsRouteWithChildren
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/status': typeof MemberStatusRoute
  '/member/submission': typeof MemberSubmissionRoute
  '/member/team': typeof MemberTeamRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/mentor/review-history': typeof MentorReviewHistoryRoute
  '/mentor/submissions': typeof MentorSubmissionsRouteWithChildren
  '/app/submission/clarification': typeof AppSubmissionClarificationRoute
  '/app/submission/confirmation': typeof AppSubmissionConfirmationRoute
  '/app/submission/preview': typeof AppSubmissionPreviewRoute
  '/app/submission/status': typeof AppSubmissionStatusRoute
  '/app/team/invite': typeof AppTeamInviteRoute
  '/judge/projects/$submissionId': typeof JudgeProjectsSubmissionIdRoute
  '/mentor/submissions/$submissionId': typeof MentorSubmissionsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/prizes': typeof PrizesRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/timeline': typeof TimelineRoute
  '/tracks': typeof TracksRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/judge-assignments': typeof AdminJudgeAssignmentsRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/mentor-assignments': typeof AdminMentorAssignmentsRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shortlist': typeof AdminShortlistRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/submission': typeof AppSubmissionRouteWithChildren
  '/app/team': typeof AppTeamRouteWithChildren
  '/judge/completed': typeof JudgeCompletedRoute
  '/judge/dashboard': typeof JudgeDashboardRoute
  '/judge/projects': typeof JudgeProjectsRouteWithChildren
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/status': typeof MemberStatusRoute
  '/member/submission': typeof MemberSubmissionRoute
  '/member/team': typeof MemberTeamRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/mentor/review-history': typeof MentorReviewHistoryRoute
  '/mentor/submissions': typeof MentorSubmissionsRouteWithChildren
  '/app/submission/clarification': typeof AppSubmissionClarificationRoute
  '/app/submission/confirmation': typeof AppSubmissionConfirmationRoute
  '/app/submission/preview': typeof AppSubmissionPreviewRoute
  '/app/submission/status': typeof AppSubmissionStatusRoute
  '/app/team/invite': typeof AppTeamInviteRoute
  '/judge/projects/$submissionId': typeof JudgeProjectsSubmissionIdRoute
  '/mentor/submissions/$submissionId': typeof MentorSubmissionsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/prizes': typeof PrizesRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/timeline': typeof TimelineRoute
  '/tracks': typeof TracksRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/judge-assignments': typeof AdminJudgeAssignmentsRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/mentor-assignments': typeof AdminMentorAssignmentsRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shortlist': typeof AdminShortlistRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/submission': typeof AppSubmissionRouteWithChildren
  '/app/team': typeof AppTeamRouteWithChildren
  '/judge/completed': typeof JudgeCompletedRoute
  '/judge/dashboard': typeof JudgeDashboardRoute
  '/judge/projects': typeof JudgeProjectsRouteWithChildren
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/status': typeof MemberStatusRoute
  '/member/submission': typeof MemberSubmissionRoute
  '/member/team': typeof MemberTeamRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/mentor/review-history': typeof MentorReviewHistoryRoute
  '/mentor/submissions': typeof MentorSubmissionsRouteWithChildren
  '/app/submission/clarification': typeof AppSubmissionClarificationRoute
  '/app/submission/confirmation': typeof AppSubmissionConfirmationRoute
  '/app/submission/preview': typeof AppSubmissionPreviewRoute
  '/app/submission/status': typeof AppSubmissionStatusRoute
  '/app/team/invite': typeof AppTeamInviteRoute
  '/judge/projects/$submissionId': typeof JudgeProjectsSubmissionIdRoute
  '/mentor/submissions/$submissionId': typeof MentorSubmissionsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/login'
    | '/prizes'
    | '/register'
    | '/rules'
    | '/timeline'
    | '/tracks'
    | '/admin/dashboard'
    | '/admin/exports'
    | '/admin/judge-assignments'
    | '/admin/judges'
    | '/admin/mentor-assignments'
    | '/admin/mentors'
    | '/admin/participants'
    | '/admin/scores'
    | '/admin/settings'
    | '/admin/shortlist'
    | '/admin/submissions'
    | '/admin/teams'
    | '/admin/winners'
    | '/app/dashboard'
    | '/app/onboarding'
    | '/app/submission'
    | '/app/team'
    | '/judge/completed'
    | '/judge/dashboard'
    | '/judge/projects'
    | '/member/dashboard'
    | '/member/status'
    | '/member/submission'
    | '/member/team'
    | '/mentor/dashboard'
    | '/mentor/review-history'
    | '/mentor/submissions'
    | '/app/submission/clarification'
    | '/app/submission/confirmation'
    | '/app/submission/preview'
    | '/app/submission/status'
    | '/app/team/invite'
    | '/judge/projects/$submissionId'
    | '/mentor/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/login'
    | '/prizes'
    | '/register'
    | '/rules'
    | '/timeline'
    | '/tracks'
    | '/admin/dashboard'
    | '/admin/exports'
    | '/admin/judge-assignments'
    | '/admin/judges'
    | '/admin/mentor-assignments'
    | '/admin/mentors'
    | '/admin/participants'
    | '/admin/scores'
    | '/admin/settings'
    | '/admin/shortlist'
    | '/admin/submissions'
    | '/admin/teams'
    | '/admin/winners'
    | '/app/dashboard'
    | '/app/onboarding'
    | '/app/submission'
    | '/app/team'
    | '/judge/completed'
    | '/judge/dashboard'
    | '/judge/projects'
    | '/member/dashboard'
    | '/member/status'
    | '/member/submission'
    | '/member/team'
    | '/mentor/dashboard'
    | '/mentor/review-history'
    | '/mentor/submissions'
    | '/app/submission/clarification'
    | '/app/submission/confirmation'
    | '/app/submission/preview'
    | '/app/submission/status'
    | '/app/team/invite'
    | '/judge/projects/$submissionId'
    | '/mentor/submissions/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/login'
    | '/prizes'
    | '/register'
    | '/rules'
    | '/timeline'
    | '/tracks'
    | '/admin/dashboard'
    | '/admin/exports'
    | '/admin/judge-assignments'
    | '/admin/judges'
    | '/admin/mentor-assignments'
    | '/admin/mentors'
    | '/admin/participants'
    | '/admin/scores'
    | '/admin/settings'
    | '/admin/shortlist'
    | '/admin/submissions'
    | '/admin/teams'
    | '/admin/winners'
    | '/app/dashboard'
    | '/app/onboarding'
    | '/app/submission'
    | '/app/team'
    | '/judge/completed'
    | '/judge/dashboard'
    | '/judge/projects'
    | '/member/dashboard'
    | '/member/status'
    | '/member/submission'
    | '/member/team'
    | '/mentor/dashboard'
    | '/mentor/review-history'
    | '/mentor/submissions'
    | '/app/submission/clarification'
    | '/app/submission/confirmation'
    | '/app/submission/preview'
    | '/app/submission/status'
    | '/app/team/invite'
    | '/judge/projects/$submissionId'
    | '/mentor/submissions/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrizesRoute: typeof PrizesRoute
  RegisterRoute: typeof RegisterRoute
  RulesRoute: typeof RulesRoute
  TimelineRoute: typeof TimelineRoute
  TracksRoute: typeof TracksRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExportsRoute: typeof AdminExportsRoute
  AdminJudgeAssignmentsRoute: typeof AdminJudgeAssignmentsRoute
  AdminJudgesRoute: typeof AdminJudgesRoute
  AdminMentorAssignmentsRoute: typeof AdminMentorAssignmentsRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminScoresRoute: typeof AdminScoresRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShortlistRoute: typeof AdminShortlistRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminWinnersRoute: typeof AdminWinnersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSubmissionRoute: typeof AppSubmissionRouteWithChildren
  AppTeamRoute: typeof AppTeamRouteWithChildren
  JudgeCompletedRoute: typeof JudgeCompletedRoute
  JudgeDashboardRoute: typeof JudgeDashboardRoute
  JudgeProjectsRoute: typeof JudgeProjectsRouteWithChildren
  MemberDashboardRoute: typeof MemberDashboardRoute
  MemberStatusRoute: typeof MemberStatusRoute
  MemberSubmissionRoute: typeof MemberSubmissionRoute
  MemberTeamRoute: typeof MemberTeamRoute
  MentorDashboardRoute: typeof MentorDashboardRoute
  MentorReviewHistoryRoute: typeof MentorReviewHistoryRoute
  MentorSubmissionsRoute: typeof MentorSubmissionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes': {
      id: '/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof PrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/submissions': {
      id: '/mentor/submissions'
      path: '/mentor/submissions'
      fullPath: '/mentor/submissions'
      preLoaderRoute: typeof MentorSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/review-history': {
      id: '/mentor/review-history'
      path: '/mentor/review-history'
      fullPath: '/mentor/review-history'
      preLoaderRoute: typeof MentorReviewHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/dashboard': {
      id: '/mentor/dashboard'
      path: '/mentor/dashboard'
      fullPath: '/mentor/dashboard'
      preLoaderRoute: typeof MentorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/team': {
      id: '/member/team'
      path: '/member/team'
      fullPath: '/member/team'
      preLoaderRoute: typeof MemberTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/submission': {
      id: '/member/submission'
      path: '/member/submission'
      fullPath: '/member/submission'
      preLoaderRoute: typeof MemberSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/status': {
      id: '/member/status'
      path: '/member/status'
      fullPath: '/member/status'
      preLoaderRoute: typeof MemberStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/dashboard': {
      id: '/member/dashboard'
      path: '/member/dashboard'
      fullPath: '/member/dashboard'
      preLoaderRoute: typeof MemberDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/projects': {
      id: '/judge/projects'
      path: '/judge/projects'
      fullPath: '/judge/projects'
      preLoaderRoute: typeof JudgeProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/dashboard': {
      id: '/judge/dashboard'
      path: '/judge/dashboard'
      fullPath: '/judge/dashboard'
      preLoaderRoute: typeof JudgeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/completed': {
      id: '/judge/completed'
      path: '/judge/completed'
      fullPath: '/judge/completed'
      preLoaderRoute: typeof JudgeCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team': {
      id: '/app/team'
      path: '/app/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/submission': {
      id: '/app/submission'
      path: '/app/submission'
      fullPath: '/app/submission'
      preLoaderRoute: typeof AppSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/winners': {
      id: '/admin/winners'
      path: '/admin/winners'
      fullPath: '/admin/winners'
      preLoaderRoute: typeof AdminWinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shortlist': {
      id: '/admin/shortlist'
      path: '/admin/shortlist'
      fullPath: '/admin/shortlist'
      preLoaderRoute: typeof AdminShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scores': {
      id: '/admin/scores'
      path: '/admin/scores'
      fullPath: '/admin/scores'
      preLoaderRoute: typeof AdminScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/admin/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mentor-assignments': {
      id: '/admin/mentor-assignments'
      path: '/admin/mentor-assignments'
      fullPath: '/admin/mentor-assignments'
      preLoaderRoute: typeof AdminMentorAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/judges': {
      id: '/admin/judges'
      path: '/admin/judges'
      fullPath: '/admin/judges'
      preLoaderRoute: typeof AdminJudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/judge-assignments': {
      id: '/admin/judge-assignments'
      path: '/admin/judge-assignments'
      fullPath: '/admin/judge-assignments'
      preLoaderRoute: typeof AdminJudgeAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exports': {
      id: '/admin/exports'
      path: '/admin/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/submissions/$submissionId': {
      id: '/mentor/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/mentor/submissions/$submissionId'
      preLoaderRoute: typeof MentorSubmissionsSubmissionIdRouteImport
      parentRoute: typeof MentorSubmissionsRoute
    }
    '/judge/projects/$submissionId': {
      id: '/judge/projects/$submissionId'
      path: '/$submissionId'
      fullPath: '/judge/projects/$submissionId'
      preLoaderRoute: typeof JudgeProjectsSubmissionIdRouteImport
      parentRoute: typeof JudgeProjectsRoute
    }
    '/app/team/invite': {
      id: '/app/team/invite'
      path: '/invite'
      fullPath: '/app/team/invite'
      preLoaderRoute: typeof AppTeamInviteRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/app/submission/status': {
      id: '/app/submission/status'
      path: '/status'
      fullPath: '/app/submission/status'
      preLoaderRoute: typeof AppSubmissionStatusRouteImport
      parentRoute: typeof AppSubmissionRoute
    }
    '/app/submission/preview': {
      id: '/app/submission/preview'
      path: '/preview'
      fullPath: '/app/submission/preview'
      preLoaderRoute: typeof AppSubmissionPreviewRouteImport
      parentRoute: typeof AppSubmissionRoute
    }
    '/app/submission/confirmation': {
      id: '/app/submission/confirmation'
      path: '/confirmation'
      fullPath: '/app/submission/confirmation'
      preLoaderRoute: typeof AppSubmissionConfirmationRouteImport
      parentRoute: typeof AppSubmissionRoute
    }
    '/app/submission/clarification': {
      id: '/app/submission/clarification'
      path: '/clarification'
      fullPath: '/app/submission/clarification'
      preLoaderRoute: typeof AppSubmissionClarificationRouteImport
      parentRoute: typeof AppSubmissionRoute
    }
  }
}

interface AppSubmissionRouteChildren {
  AppSubmissionClarificationRoute: typeof AppSubmissionClarificationRoute
  AppSubmissionConfirmationRoute: typeof AppSubmissionConfirmationRoute
  AppSubmissionPreviewRoute: typeof AppSubmissionPreviewRoute
  AppSubmissionStatusRoute: typeof AppSubmissionStatusRoute
}

const AppSubmissionRouteChildren: AppSubmissionRouteChildren = {
  AppSubmissionClarificationRoute: AppSubmissionClarificationRoute,
  AppSubmissionConfirmationRoute: AppSubmissionConfirmationRoute,
  AppSubmissionPreviewRoute: AppSubmissionPreviewRoute,
  AppSubmissionStatusRoute: AppSubmissionStatusRoute,
}

const AppSubmissionRouteWithChildren = AppSubmissionRoute._addFileChildren(
  AppSubmissionRouteChildren,
)

interface AppTeamRouteChildren {
  AppTeamInviteRoute: typeof AppTeamInviteRoute
}

const AppTeamRouteChildren: AppTeamRouteChildren = {
  AppTeamInviteRoute: AppTeamInviteRoute,
}

const AppTeamRouteWithChildren =
  AppTeamRoute._addFileChildren(AppTeamRouteChildren)

interface JudgeProjectsRouteChildren {
  JudgeProjectsSubmissionIdRoute: typeof JudgeProjectsSubmissionIdRoute
}

const JudgeProjectsRouteChildren: JudgeProjectsRouteChildren = {
  JudgeProjectsSubmissionIdRoute: JudgeProjectsSubmissionIdRoute,
}

const JudgeProjectsRouteWithChildren = JudgeProjectsRoute._addFileChildren(
  JudgeProjectsRouteChildren,
)

interface MentorSubmissionsRouteChildren {
  MentorSubmissionsSubmissionIdRoute: typeof MentorSubmissionsSubmissionIdRoute
}

const MentorSubmissionsRouteChildren: MentorSubmissionsRouteChildren = {
  MentorSubmissionsSubmissionIdRoute: MentorSubmissionsSubmissionIdRoute,
}

const MentorSubmissionsRouteWithChildren =
  MentorSubmissionsRoute._addFileChildren(MentorSubmissionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PrizesRoute: PrizesRoute,
  RegisterRoute: RegisterRoute,
  RulesRoute: RulesRoute,
  TimelineRoute: TimelineRoute,
  TracksRoute: TracksRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExportsRoute: AdminExportsRoute,
  AdminJudgeAssignmentsRoute: AdminJudgeAssignmentsRoute,
  AdminJudgesRoute: AdminJudgesRoute,
  AdminMentorAssignmentsRoute: AdminMentorAssignmentsRoute,
  AdminMentorsRoute: AdminMentorsRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminScoresRoute: AdminScoresRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShortlistRoute: AdminShortlistRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminWinnersRoute: AdminWinnersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSubmissionRoute: AppSubmissionRouteWithChildren,
  AppTeamRoute: AppTeamRouteWithChildren,
  JudgeCompletedRoute: JudgeCompletedRoute,
  JudgeDashboardRoute: JudgeDashboardRoute,
  JudgeProjectsRoute: JudgeProjectsRouteWithChildren,
  MemberDashboardRoute: MemberDashboardRoute,
  MemberStatusRoute: MemberStatusRoute,
  MemberSubmissionRoute: MemberSubmissionRoute,
  MemberTeamRoute: MemberTeamRoute,
  MentorDashboardRoute: MentorDashboardRoute,
  MentorReviewHistoryRoute: MentorReviewHistoryRoute,
  MentorSubmissionsRoute: MentorSubmissionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
